pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0.x'

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: 'build'
    dockerfile: '**/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    imageName: 'azurecontainerimage'

- task: Docker@2
  displayName: 'Save Docker image'
  inputs:
    command: 'save'
    dockerRepository: 'azurecontainerimage'
    savePath: '$(Build.ArtifactStagingDirectory)/docker-image.tar'